---
# tasks file for openstack-neutron
- name: ensure neutron database is present
  mysql_db:
    name: neutron

- name: ensure neutron database user is present
  mysql_user:
    name: neutron
    host: "{{ item }}"
    password: "{{ neutron_mysql_password }}"
    priv: neutron.*:ALL
  with_items:
    - "%"
    - localhost

- name: create neutron service user
  keystone_user:
    endpoint: "{{ keystone_bootstrap_endpoint }}"
    token: "{{ keystone_admin_token }}"
    tenant: service
    user: neutron
    password: "{{ neutron_identity_password }}"

- name: add neutron service user to the service tenant with the admin role
  keystone_user:
    endpoint: "{{ keystone_bootstrap_endpoint }}"
    token: "{{ keystone_admin_token }}"
    tenant: service
    user: neutron
    role: admin

- name: add neutron endpoint to keystone
  keystone_service:
    endpoint: "{{ keystone_bootstrap_endpoint }}"
    token: "{{ keystone_admin_token }}"
    region: "{{ openstack_region }}"
    name: neutron
    type: network
    description: "Networking Service"
    public_url: "{{ neutron_public_url }}"
    internal_url: "{{ neutron_internal_url }}"
    admin_url: "{{ neutron_admin_url }}"

- name: ensure {{ component }}-{{ subcomponent }} packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openstack-{{ component }}
    - openstack-neutron-ml2
    - python-neutronclient
    - which

- name: ensure services are stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - "{{ component }}-{{ subcomponent }}"

- name: ensure {{ component }} sqlite is deleted
  file:
    dest: /var/lib/{{ component }}/{{ component }}.sqlite
    state: absent

- name: update configuration files from templates
  template:
    src: templates/etc/{{ component }}/{{ item }}
    dest: /etc/{{ component }}/{{ item }}
    owner: "{{ component }}"
    group: "{{ component }}"
    mode: 0600
  with_items:
    - dhcp_agent.ini
    - l3_agent.ini
    - metadata_agent.ini
    - "{{ component }}.conf"

- name: update ml2_conf.ini from template
  template:
    src: templates/etc/neutron/plugins/ml2/ml2_conf.ini
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    owner: neutron
    group: neutron
    mode: 0600

- name: make sure symlink to ml2_conf.ini exists
  file:
    src: /etc/neutron/plugins/ml2/ml2_conf.ini
    dest: /etc/neutron/plugin.ini
    state: link

- name: ensure database is synced
  command: /usr/bin/{{ component }}-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head

- name: ensure services are started and enabled
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - "{{ component }}-{{ subcomponent }}"

- name: wait for neutron to come back up
  wait_for:
    host: "{{ keystone_endpoint_host }}"
    port: 9696
