---
# tasks file for docker
- include: "{{ ansible_os_family }}.yml"
  when: upstream_docker == true

- name: (Upstream Docker selected) Install docker
  package:
    state: present
    name: docker-ce
  when: upstream_docker == true

- name: (Red Hat) Install docker
  package:
    state: present
    name: docker
  when: (ansible_os_family == "RedHat" and upstream_docker == false)

- name: (Debian) Install docker
  package:
    state: present
    name: docker.io
  when: (ansible_os_family == "Debian" and upstream_docker == false)

- name: Install docker-image-clean script
  copy:
    src: docker-image-clean
    dest: /etc/cron.weekly
    mode: 0755

- name: ensure Docker is started and enabled
  service:
    name: docker
    state: started
    enabled: yes
