---
# tasks file for epel-repo
- name: Install epel repo
  package:
    name: epel-release
    state: present
- name: Install yum plugin for priorities
  package:
    name: yum-plugin-priorities
    state: present
